# Finding local extremum (maximum/minimum) from the data samples

In this tutorial, local maxima and minima will be idenfied using second derivative test.

Necessary Conditions for a point of data in the data samples to be local maximum/minimum are as follows:

1. The points/point where
                       second derivative > 0 then it is  Local MINIMUM
               
               
2. The points/point where
                       second derivative < 0 then it is  Local MAXIMUM
                     

Let's start with very simple example. First import the necessary library.


In [97]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [98]:
A=np.array([2, 5, 1, 7, 3, 3])
print(A)
fig = go.Figure(data=go.Scatter(y=A))
fig.show()

[2 5 1 7 3 3]


We will identify the extremums (turning points) in array A (as seen above min points: {1,3} with index [2,4] and max points: {5,7} with index [1,3]).  To get second derivative of A:
1. take first derivative of A , 
            first_derivative=np.diff(A)
2. take first derivative of first_derivative , 
            second_derivative=np.diff(first_derivative)

In [99]:
first_derivative=np.diff(A)
print('first derivative:', first_derivative)   # notice number of elements in 'first_derivative' will be 'length(A)-1'

first derivative: [ 3 -4  6 -4  0]


In [100]:
second_derivative=np.diff(first_derivative)
print('second derivative:', second_derivative)  # notice number of elements in 'first_derivative' will be 'length(A)-2'

second derivative: [ -7  10 -10   4]


Look at the above values from second derivative. Values in index poistions [0,2] indicates local maxima (because second_derivative < 0). However, as we pointed out before, the indexes of actual local maxima are [1,3]. So, by adding 1 to the index poistions of second_derivative values we can get the actual index positions of local maxima. Same is true for local Minima.

**For Local Minimum:**

In [101]:
second_derivative_index_Min= (second_derivative>0)
print(second_derivative_index_Min)

[False  True False  True]


In [102]:
second_derivative_index_Min=second_derivative_index_Min.nonzero()  # identify the location
print(second_derivative_index_Min)


(array([1, 3], dtype=int64),)


In [103]:
Actual_index_Lmin=second_derivative_index_Min[0]+1
print('Actual indexes of local Min: ',Actual_index_Lmin)        # see this matches the original Lmin indexes i.e [2, 4]

Actual indexes of local Min:  [2 4]


**Similarly for Local Maximum:**

In [104]:
second_derivative_index_Max= (second_derivative<0)
print(second_derivative_index_Max)

[ True False  True False]


In [105]:
second_derivative_index_Max=second_derivative_index_Max.nonzero()  # identify the location
print(second_derivative_index_Max)


(array([0, 2], dtype=int64),)


In [106]:
Actual_index_Lmax=second_derivative_index_Max[0]+1
print('Actual indexes of local Max: ',Actual_index_Lmax)        # see this matches the original Lmin indexes i.e [1, 3]

Actual indexes of local Max:  [1 3]


In [107]:
#Local_maxima=A[Actual_index_Lmax]
#Local_mimima=A[Actual_index_Lmin]
x=np.arange(len(A))

In [108]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=A,
                    name='Original data'))

fig.add_trace(go.Scatter(x=x[Actual_index_Lmax], y=A[Actual_index_Lmax],
                    mode="markers", name='Local Maxima'))

fig.add_trace(go.Scatter(x=x[Actual_index_Lmin], y=A[Actual_index_Lmin],
                    mode="markers", name='Local Minima'))

**Concise implementation example**

In [109]:
y_data=np.array([1, 2, 5, 0, 0, 30, 35, 15, 10])
x_data=np.arange(len(y_data))

In [110]:
Lmin_indexes=(np.diff(np.diff(y_data))>0).nonzero()[0]+1
print(Lmin_indexes)

[1 3 4 7]


In [111]:
Lmax_indexes=(np.diff(np.diff(y_data))<0).nonzero()[0]+1
print(Lmax_indexes)

[2 5 6]


In [112]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x_data, y=y_data,
                    name='Original data'))

fig.add_trace(go.Scatter(x=x_data[Lmax_indexes], y=y_data[Lmax_indexes],
                    mode="markers", name='Local Maxima'))

fig.add_trace(go.Scatter(x=x_data[Lmin_indexes], y=y_data[Lmin_indexes],
                    mode="markers", name='Local Minima'))